# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-21 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurantlocation_my_date_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='my_date_field',
        ),
    ]
